// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmnnssxpmzefypocuuya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdtbm5zc3hwbXplZnlwb2N1dXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Mzk5NTksImV4cCI6MjA2MTMxNTk1OX0.NstNyE6OBshbUnoNCJJTy6UFP4Wtf-24itxWinVwKtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);